#!/usr/bin/python
# -*- coding:utf-8 -*-

country_list={
"VC":u"St. Vincent and The Grenadines",
"TC":u"Turks and Caicos",
"GB":u"イギリス",
"IS":u"アイスランド",
"IE":u"アイルランド",
"AZ":u"アゼルバイジャン",
"AE":u"アラブ首長国連邦",
"DZ":u"アルジェリア",
"AR":u"アルゼンチン",
"AL":u"アルバニア",
"AM":u"アルメニア",
"AI":u"アンギラ",
"AO":u"アンゴラ",
"AG":u"アンティグア･バーブーダ",
"YE":u"イエメン",
"VG":u"イギリス領ヴァージン諸島",
"IL":u"イスラエル",
"IT":u"イタリア",
"IN":u"インド",
"ID":u"インドネシア",
"UG":u"ウガンダ",
"UA":u"ウクライナ",
"UZ":u"ウズベキスタン",
"UY":u"ウルグアイ",
"EC":u"エクアドル",
"EG":u"エジプト",
"EE":u"エストニア",
"SV":u"エルサルバドル",
"AU":u"オーストラリア",
"AT":u"オーストリア",
"OM":u"オマーン",
"NL":u"オランダ",
"CV":u"カーボベルデ",
"GY":u"ガイアナ",
"KZ":u"カザフスタン",
"QA":u"カタール",
"CA":u"カナダ",
"GM":u"ガンビア",
"KH":u"カンボジア",
"GH":u"ガーナ",
"GW":u"ギニアビサウ",
"CY":u"キプロス",
"GR":u"ギリシャ",
"KG":u"キルギスタン",
"GT":u"グアテマラ",
"KW":u"クウェート",
"GD":u"グレナダ",
"HR":u"クロアチア",
"KY":u"ケイマン諸島",
"KE":u"ケニア",
"CR":u"コスタリカ",
"CO":u"コロンビア",
"CG":u"コンゴ共和国",
"SA":u"サウジアラビア",
"ST":u"サントメプリンシペ",
"SL":u"シエラレオネ",
"JM":u"ジャマイカ",
"SG":u"シンガポール",
"ZW":u"ジンバブエ",
"CH":u"スイス",
"SE":u"スウェーデン",
"ES":u"スペイン",
"SR":u"スリナム",
"LK":u"スリランカ",
"SK":u"スロバキア",
"SI":u"スロベニア",
"SZ":u"スワジランド",
"SC":u"セーシェル",
"SN":u"セネガル",
"KN":u"セントクリストファー・ネイビス",
"LC":u"セントルシア",
"SB":u"ソロモン諸島",
"TH":u"タイ",
"TJ":u"タジキスタン",
"TZ":u"タンザニア",
"CZ":u"チェコ共和国",
"TD":u"チャド",
"TN":u"チュニジア",
"CL":u"チリ",
"DK":u"デンマーク",
"DE":u"ドイツ",
"DO":u"ドミニカ共和国",
"DM":u"ドミニカ国",
"TT":u"トリニダード・トバゴ",
"TM":u"トルクメニスタン",
"TR":u"トルコ",
"NG":u"ナイジェリア",
"NE":u"ナイジャ",
"NA":u"ナミビア",
"NI":u"ニカラグア",
"NZ":u"ニュージーランド",
"NP":u"ネパール",
"NO":u"ノルウェー",
"PK":u"パキスタン",
"PA":u"パナマ",
"BS":u"バハマ",
"PG":u"パプアニューギニア",
"BM":u"バミューダ",
"PW":u"パラオ",
"PY":u"パラグアイ",
"BB":u"バルバドス",
"HU":u"ハンガリー",
"BH":u"バーレーン",
"FJ":u"フィジー",
"PH":u"フィリピン",
"FI":u"フィンランド",
"BR":u"ブラジル",
"FR":u"フランス",
"BG":u"ブルガリア",
"BF":u"ブルキナファソ",
"BN":u"ブルネイ",
"BT":u"ブータン",
"VN":u"ベトナム",
"BJ":u"ベナン",
"VE":u"ベネズエラ",
"BY":u"ベラルーシ",
"BZ":u"ベリーズ",
"PE":u"ペルー",
"BE":u"ベルギー",
"BW":u"ボツワナ",
"BO":u"ボリビア",
"PT":u"ポルトガル",
"HN":u"ホンジュラス",
"PL":u"ポーランド",
"MO":u"マカオ",
"MK":u"マケドニア",
"MG":u"マダガスカル",
"MW":u"マラウイ",
"ML":u"マリ",
"MT":u"マルタ",
"MY":u"マレーシア",
"FM":u"ミクロネシア連邦",
"MX":u"メキシコ",
"MU":u"モーリシャス",
"MR":u"モーリタニア",
"MZ":u"モザンビーク",
"MD":u"モルドバ",
"MN":u"モンゴル",
"MS":u"モントセラト",
"JO":u"ヨルダン",
"LA":u"ラオス人民民主共和国",
"LV":u"ラトビア",
"LT":u"リトアニア",
"LR":u"リベリア",
"RO":u"ルーマニア",
"LU":u"ルクセンブルク",
"LB":u"レバノン",
"RU":u"ロシア",
"KR":u"韓国",
"HK":u"香港",
"TW":u"台湾",
"CN":u"中国",
"ZA":u"南アフリカ",
"JP":u"日本",
"US":u"アメリカ合衆国"}
media_type={
"Mobile Software Applications":u"iOS Apps",
"iTunes U":u"iTunes U",
"Desktop Apps":u"Mac App",
"Podcasts":u"Podcast",
"Audiobooks":u"オーディオブック",
"E-Books":u"ブック",
"Music":u"ミュージック",
"Music Videos":u"ミュージックビデオ",
"Movies":u"映画",
}
feed_type={
    "Mobile Software Applications":{
        "topfreeapplications":u"トップ無料 App",
        "toppaidapplications":u"トップ有料 App",
        "topgrossingapplications":u"トップセールス App",
        "topfreeipadapplications":u"トップ無料 iPad App",
        "toppaidipadapplications":u"トップ有料 iPad App",
        "topgrossingipadapplications":u"トップセールス iPad App",
        "newapplications":u"新規 App",
        "newfreeapplications":u"新規無料 App",
        "newpaidapplications":u"新規有料 App",
        },
    }
def main():
    for k in country_list:
        print k,country_list[k]
if __name__=='__main__':main()
